### ISSUE TITLE
Registration URL has changed

### ISSUE THREAD

**Issue by timur-tabi** [MallocArray/thespaghettidetective-oraclecloud#2]
I suggest instead of posting a specific URL, you provide more general instructions.

1) Go to https://www.oracle.com/cloud/
2) Click on the link "Try OCI for free"
3) Click on the link "Start for free" and follow the instructions

**Comment by timur-tabi** [comment]
You might also want to add that you'll need to provide a credit card even for a free account.

**Comment by MallocArray** [comment]
Thank you.  Updated in the new Obico project, as this one is no longer maintained and has a link to the new one.

https://github.com/MallocArray/obico-oraclecloud
